Config = Config or {}

Config.RepeatTimeout = 3300
Config.LigandoTimeout = 12800
Config.CallRepeats = 6
Config.OpenPhone = 311
Config.PhoneApplications = {
    ["phone"] = {
        app = "phone",
        color = "#04b543",
        icon = "telefone",
        tooltipText = "Phone",
        tooltipPos = "top",
        nome = "",
        job = false,
        blockedjobs = {},
        slot = 1,
        Alerts = 0,
    },
    ["whatsapp"] = {
        app = "whatsapp",
        color = "#127ED7",
        icon = "sms",
        nome = "",
        tooltipText = "SMS",
        tooltipPos = "top",
        style = "font-size: 2.8vh";
        job = false,
        blockedjobs = {},
        slot = 2,
        Alerts = 0,
    },
    ["settings"] = {
        app = "settings",
        color = "#636e72",
        icon = "ajustes",
        tooltipText = "Settings",
        nome = "",
        tooltipPos = "top",
        style = "padding-right: .08vh; font-size: 2.3vh";
        job = false,
        blockedjobs = {},
        slot = 3,
        Alerts = 0,
    },
    ["twitter"] = {
        app = "twitter",
        color = "#1da1f2",
        icon = "twitter",
        tooltipText = "Twitter",
        nome = "",
        tooltipPos = "top",
        job = false,
        blockedjobs = {},
        slot = 4,
        Alerts = 0,
    },
    -- ["houses"] = {
    --     app = "houses",
    --     color = "gold",
    --     icon = "residencias",
    --     tooltipText = "Casas",
    --     job = false,
    --     blockedjobs = {},
    --     slot = 5,
    --     Alerts = 0,
    -- },
    ["mail"] = {
        app = "mail",
        color = "purple",
        icon = "mail",
        tooltipText = "Caixa de Entrada",
        nome = "Mail",
        job = false,
        blockedjobs = {},
        slot = 5,
        Alerts = 0,
    },
    ["advert"] = {
        app = "advert",
        color = "orange",
        icon = "anunciar",
        tooltipText = "Anuncie",
        nome = "Rebay",
        job = false,
        blockedjobs = {},
        slot = 6,
        Alerts = 0,
    },

    ["bank"] = {
        app = "bank",
        color = "lightgreen",
        icon = "banco",
        tooltipText = "Banco",
        nome = "Banco",
        job = false,
        blockedjobs = {},
        slot = 7,
        Alerts = 0,
    },

    ["garage"] = {
        app = "garage",
        color = "#575fcf",
        icon = "garagem",
        tooltipText = "Garagem",
        nome = "Carros",
        job = false,
        blockedjobs = {},
        slot = 8,
        Alerts = 0,
    },
    -- ["lawyers"] = {
    --     app = "lawyers",
    --     color = "#353b48",
    --     icon = "advogados",
    --     tooltipText = "Advogados",
    --     job = false,
    --     blockedjobs = {},
    --     slot = 10,
    --     Alerts = 0,
    -- },
    ["camera"] = {
        app = "camera",
        color = "#004682",
        icon = "camera",
        nome = "Camera",
        tooltipText = "Camera",
        job = false,
        blockedjobs = {},
        slot = 9,
        Alerts = 0,
    },
    ["instagram"] = {
        app = "instagram",
        color = "#004682",
        icon = "instagram",
        tooltipText = "Instagram",
        nome = "Instaborn",
        job = false,
        blockedjobs = {},
        slot = 10,
        Alerts = 0,
    },
    ["meos"] = {
        app = "meos",
        color = "#004682",
        icon = "policia",
        nome = "Policia",
        tooltipText = "MDT",
        job = "police",
        blockedjobs = {},
        slot = 11,
        Alerts = 0,
    },
        -- ["advert"] = {
    --     app = "advert",
    --     color = "orange",
    --     icon = "fab fa-adversal",
    --     tooltipText = "Adverts",
    --     job = false,
    --     blockedjobs = {},
    --     slot = 7,
    --     Alerts = 0,
    -- },
        -- ["crypto"] = {
    --     app = "crypto",
    --     color = "#D2691E",
    --     icon = "fab fa-btc",
    --     tooltipText = "Your Bitcoin Wallet",
    --     job = false,
    --     blockedjobs = {},
    --     slot = 9,
    --     Alerts = 0,
    -- },

    -- ["racing"] = {
    --     app = "racing",
    --     color = "#353b48",
    --     icon = "fas fa-flag-checkered",
    --     tooltipText = "Racing",
    --     job = false,
    --     blockedjobs = {
    --         "police"
    --     },
    --     slot = 20,
    --     Alerts = 0,
    -- },
    -- ["trabalhar"] = {
    --     app = "trabalhar",
    --     color = "#353b48",
    --     icon = "fas fa-gavel",
    --     tooltipText = "Trabalhar",
    --     tooltipPos = "right",
    --     job = false,
    --     blockedjobs = {},
    --     slot = 14,
    --     Alerts = 0,
    -- },
}